ARDUINO_DIR = /home/daddel9/arduino/
BOARD_TAG      = sanguino
BOARD_SUB      = atmega1284p
ARDUINO_LIBS   = U8glib
ALTERNATE_CORE =
ALTERNATE_CORE_PATH = /home/daddel9/.arduino15/packages/Sanguino/hardware/avr/1.0.2
ARDUINO_VAR_PATH    = /home/daddel9/.arduino15/packages/Sanguino/hardware/avr/1.0.2/variants/sanguino
ARDUINO_CORE_PATH   = /home/daddel9/arduino/hardware/arduino/avr/cores/arduino
BOOTLOADER_PARENT   = ~/.arduino15/packages/Sanguino/hardware/avr/1.0.2/bootloaders
ARDUINO_PORT   = /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AH01QH7S-if00-port0
AVRDUDE_ARD_PROGRAMMER = stk500v1
MONITOR_BAUDRATE = 115200
EXTRA_FLAGS    = -std=c++14 -fno-threadsafe-statics -Wp,-w -flto -fdata-sections -ffunction-sections -Wl,-gc-sections -gstabs -fshort-enums -mcall-prologues Wl,--relax --param inline-call-cost=2 --combine -fwhole-program
AVRDUDE_OPTS   = -V
OPTIMIZATION_LEVEL=s

USER_LIB_PATH := $(realpath ../common)

include /home/daddel9/sources/Arduino-Makefile/Arduino.mk

